export const Endpoint = {
  checkEmail: "auth/checkEmail",
  signup: "auth/signup",
  verifyOTP: "auth/verifyOTP",
  resendOtp: "auth/resendOtp",
  login: "auth/login",
  profile: "auth/profile",
  editSetting: "auth/editSetting",
  changePassword: "auth/change-password",
  forgotPassword: "auth/forgot-password",
  resetPassword: "auth/reset-password",
  cms: "home/getCms",
  faq: "home/getFaq",
  map: "home/getmap",
  contact: "home/contact",
  getSingleAttack: "home/getSingleAttack",
  addQuest: "quest/add",
  getQuest: "quest/get",
  getSingleQuest: "quest/single",
  answer: "quest/answer",
  markAsComplete: "quest/markAsComplete",
  statistics: "quest/statistics",
  getGlobalSetting: "home/getGlobalSetting",
  credits: "quest/credits",
  topUp: "quest/topUp",
  stripePay: "quest/stripePay",
};
